
name: Run Tests with PNPM and Vitest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Install dependencies
        run: pnpm install

      - name: Run Vitest tests
        run: pnpm run test
        env:  # Set your environment variables here
          PORT:  ${{ secrets.PORT }} 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Store your real database URL in GitHub Secrets
        continue-on-error: true  # Ensure failure notification runs

      - name: Generate Test Report
        if: always()
        run: |
          pnpm run test --reporter=json --output-file=test-report.json
          cat test-report.json
        continue-on-error: true

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./test-report.json

      - name: Annotate Test Failures
        if: failure()
        uses: dorny/test-reporter@v1
        with:
          name: vitest
          path: ./test-report.json
          reporter: vitest
          max-annotations: 10
          fail-on-error: true

      # Email notification step
      - name: Send Email Notification on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}  # Your email (set this secret in GitHub)
          password: ${{ secrets.EMAIL_PASSWORD }}  # App-specific password
          subject: "Test Failure on ${{ github.repository }}"
          body: |
            :x: Tests failed in ${{ github.workflow }} for ${{ github.ref }}.
            Commit: ${{ github.sha }}
            View the detailed results: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: your-email@example.com
          from: ${{ secrets.EMAIL_USERNAME }}